# Numpy

In [42]:
import numpy as np

## Let's do some basic stuff

In [43]:
a =  np.array(5)
a

array(5)

In [44]:
b = np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### numpy functions are not inplace.

In [45]:
b = b.reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [46]:
print(b.shape)
print(b.ndim)
print(b.size)
print(b.dtype)

(3, 5)
2
15
int32


In [47]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Some Operations

In [49]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)

In [50]:
a

array([20, 30, 40, 50])

In [51]:
b

array([0, 1, 2, 3])

In [52]:
a - b

array([20, 29, 38, 47])

In [53]:
a + b

array([20, 31, 42, 53])

This is normal multiplication not matrix multiplication

In [54]:
c = a * b

In [55]:
c > 50

array([False, False,  True,  True])

In [56]:
np.sin(c)

array([ 0.        , -0.98803162, -0.99388865, -0.71487643])

In [57]:
m1 = np.arange(4)
m2 = np.arange(4)

In [58]:
m2 = m2.reshape((4, 1))
m1 = m1.reshape((1, 4))
m2

array([[0],
       [1],
       [2],
       [3]])

In [59]:
m1

array([[0, 1, 2, 3]])

This is how matrix multiplication is done in numpy

In [60]:
m1 @ m2

array([[14]])

Pandas performs better in manipulating massive data and is used instead of numpy for big data.